### ISSUE TITLE
Error when attempting to download

### ISSUE THREAD

**Issue by jin-eld** [martykan/mapycz-tile-download#3]
Hi,

I am trying to download some tiles and unfortunately it does not work. The interesting thing is: the example line from the README does work, but when I use my own coordinates it fails with an error:

```
$ npx mapycz-tile-downl tiles/ 20 48.3326433 17.1266289 48.3360667 17.1697158
info sharp Using cached /home/xxx/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz
TypeError: Cannot read property 'file' of undefined
    at composite (/home/xxx/.npm/_npx/22842/lib/node_modules/mapycz-tile-downl/index.js:48:47)
    at downloadMapyCzTiles (/home/xxx/.npm/_npx/22842/lib/node_modules/mapycz-tile-downl/index.js:99:9)
    at validateArgs (/home/xxx/.npm/_npx/22842/lib/node_modules/mapycz-tile-downl/index.js:132:3)
    at Object.<anonymous> (/home/xxx/.npm/_npx/22842/lib/node_modules/mapycz-tile-downl/index.js:137:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at /usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
Output saved
```

Is this a bug or a user error?

**Comment by martykan** [comment]
Hi, it was a bug, I've updated the code. But also the zoom level 20 is too much, 19 should work.
